export const CREATE_SPACE = "CREATE_SPACE"
export const JOIN_SPACE = "JOIN_SPACE"
export const GET_SPACES = "GET_SPACES"
export const GET_SPACE = "GET_SPACE"
export const GET_USER_SPACES = "GET_USER_SPACES"